"""CROWN-Y Tournament Build switches and conservative constants."""

from __future__ import annotations

import os


def _float_env(name: str, default: float, lo: float, hi: float) -> float:
    try:
        value = float(os.environ.get(name, default))
    except (TypeError, ValueError):
        return default
    return max(lo, min(hi, value))


SUBMIT_MODE = False

ENABLE_TIME_SHADOW = True
ENABLE_PREFERENCE_MONITOR = True
ENABLE_VISIBLE_TWO_HOP = True
ENABLE_RESOURCE_ENDGAME = True
ENABLE_SCOUT_THEN_DEEPEN = False
ENABLE_REPOSITION = False
ENABLE_LEARNED_RANKER = False
ENABLE_LLM_JUDGE = False
ENABLE_THREE_HOP = False
ENABLE_OPTION_ROLLOUT = False
OFFICIAL_ALLOW_ARBITRARY_COORD_QUERY = False
ENABLE_DESTINATION_SHADOW_QUERY = False

TRACE_LEVEL = "minimal" if SUBMIT_MODE else "full"
if SUBMIT_MODE:
    ENABLE_DESTINATION_SHADOW_QUERY = False

SIMULATION_DURATION_DAYS = 31
SIMULATION_HORIZON_MINUTES = SIMULATION_DURATION_DAYS * 24 * 60
REPOSITION_SPEED_KM_PER_HOUR = 60.0
DEFAULT_COST_PER_KM = 1.5

SCOUT_K = 50
DEEPEN_K = 120
LARGE_QUERY_K = 200
MAX_QUERY_K = 600

QUERY_BATCH_SIZE = 10
HIGH_QUERY_TIME_COST = 2.8
STRONG_ORDER_ADVANTAGE = 180.0
MIN_DEEPEN_SLACK_MINUTES = 60
ENOUGH_FEASIBLE_COUNT = 18

WAIT_MINUTES_DEFAULT = 45
WAIT_MINUTES_SHORT = 20
WAIT_MINUTES_ENDGAME = 30
MIN_WAIT_MINUTES = 5
MAX_WAIT_MINUTES = 180

GLOBAL_BASE_PRICE_PER_MIN = 0.35
MIN_PRODUCTIVE_TIME_PRICE = 0.05
MAX_PRODUCTIVE_TIME_PRICE = 2.2
ENDGAME_TIME_PRICE_CAP = 2.8
TOP1_SELF_OPPORTUNITY_DISCOUNT = 0.35
INFORMATION_OPTION_VALUE_CAP = 150.0
OPTIONALITY_LOSS_CAP = 260.0
TIME_SHADOW_MODE = "full"
TIME_PRICE_MULTIPLIER = _float_env("CROWN_Y_TIME_PRICE_MULT", 1.0, 0.6, 1.4)
GLOBAL_BASE_PRICE_PER_MIN *= TIME_PRICE_MULTIPLIER

TWO_HOP_FIRST_K = 60
TWO_HOP_SECOND_K = 12
TWO_HOP_DISCOUNT = 0.55

MAX_ENDGAME_INTENSITY = 0.95
ENDGAME_HIGH = 0.72

REPOSITION_PAYBACK_MULTIPLIER = 1.8
REPOSITION_PAYBACK_P50_MAX_MIN = 6 * 60
REPOSITION_PAYBACK_P80_MAX_MIN = 12 * 60
REPOSITION_MAX_DISTANCE_KM = 140.0
REPOSITION_MIN_DISTANCE_KM = 8.0
REPOSITION_STRONG_ORDER_THRESHOLD = 150.0

LEARNED_BLEND = 0.10
LEARNED_MAX_BLEND = 0.25
LEARNED_CAP = 120.0
LEARNED_OOD_SHRINK = 0.2

LLM_MAX_COMPILE_CALLS_PER_DRIVER = 12
LLM_MAX_JUDGE_CALLS_PER_DRIVER = 0
LLM_MAX_JUDGE_CALLS_PER_DAY = 0
LLM_TIMEOUT_SECONDS = 3.0

_VARIANT = os.environ.get("CROWN_Y_VARIANT", "").strip().lower()
if _VARIANT in {"a", "baseline", "safe_greedy"}:
    ENABLE_TIME_SHADOW = False
    ENABLE_VISIBLE_TWO_HOP = False
    ENABLE_SCOUT_THEN_DEEPEN = False
    ENABLE_REPOSITION = False
    TIME_SHADOW_MODE = "baseline_profit_per_hour"
elif _VARIANT in {"b", "no_reposition"}:
    ENABLE_REPOSITION = False
elif _VARIANT in {"no_rollout", "rollout_off"}:
    ENABLE_VISIBLE_TWO_HOP = False
elif _VARIANT in {"no_time_shadow", "time_shadow_off"}:
    ENABLE_TIME_SHADOW = False
    TIME_SHADOW_MODE = "baseline_profit_per_hour"
elif _VARIANT in {"no_scout", "fixed_scout"}:
    ENABLE_SCOUT_THEN_DEEPEN = False
elif _VARIANT in {"c", "default", ""}:
    pass

if os.environ.get("CROWN_Y_ENABLE_REPOSITION", "").strip() == "1":
    ENABLE_REPOSITION = True
if os.environ.get("CROWN_Y_DISABLE_REPOSITION", "").strip() == "1":
    ENABLE_REPOSITION = False
if os.environ.get("CROWN_Y_ENABLE_SCOUT_THEN_DEEPEN", "").strip() == "1":
    ENABLE_SCOUT_THEN_DEEPEN = True
if os.environ.get("CROWN_Y_SUBMIT_MODE", "").strip() == "1":
    SUBMIT_MODE = True
    TRACE_LEVEL = "minimal"
    ENABLE_DESTINATION_SHADOW_QUERY = False
